### ISSUE TITLE
Kill units that block our expansions

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#303]

**Comment by RaphaelRoyerRivard** [comment]
Can happen with an enemy worker blocking our nat or an overload spraying creep on it.

**Comment by RaphaelRoyerRivard** [comment]
Or a burrowed zergling...

**Comment by Unusual229** [comment]
or a creep tumor (or any other invisible unit) or a building (generally an engeneering bay).

**Comment by RaphaelRoyerRivard** [comment]
Flagging the expand as ours would force our units to defend it, thus liberating it. Would still need new code to detect invisible units.

**Comment by Unusual229** [comment]
Will not flag the expand as ours, I am pretty sure it would break a lot of stuff (every loop on our bases).
Could detect the build command failed and create a flag for "blocked" base locations, or something like that. Would that work?

**Comment by RaphaelRoyerRivard** [comment]
Yes

**Comment by Unusual229** [comment]
Each frame that a CC fails to build, I will make the baselocation has "Blocked". You should be able to determine whether its an invisible unit or not based on whether you see a unit there or not. It means that if the unit moves away and we start the CC, the baselocation will no longer be considered "Blocked", even if the unit is still around.

This will not detect the base being blocked by creep or builds, since we will not try to build there at all. So I will require an extra check for those two things.

One problem with this current solution, if a worker is stuck and tries to build a CC, we will mark that location has blocked for no reason (since the CC will fail to start). It is very unlikely, but could happen until the stuck workers issue is fixed.

**Comment by Unusual229** [comment]
Added "IsBlocked" to each BaseLocations. Should flag :
Units (invisible included)
Buildings
Creep (not tested)

Was not tested on every map. We have an issue about Base.ContainsPosition (which is used for this) not being accurate on every map. If a base is blocked, but not flagged (can be check with the debug on '4'), look at bases nearby, they might have been flagged instead. Update the issue to let me know.
https://github.com/RaphaelRoyerRivard/MicroMachine/issues/356

**Comment by RaphaelRoyerRivard** [comment]
> Donc au lieu de spam le build, si il fail, je mark sa comme blocked, j'essaie de build à la prochaine et j'enlève le flag blocked juste quand je build une autre expand.
> comme sa, ta le temps de clear le stuff, au besoin
> Pi sinon, le worker va try again pi passé à la next

**Comment by RaphaelRoyerRivard** [comment]
J'ai fait une gestion de squads qui vont clearer les blocked expands (1 unit de combat qui attaque au sol par blocked expand). J'ai testé un seul cas, celui du worker qui bloque la nat.
