### ISSUE TITLE
Postpone the production of the anti-air buildings and research

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#462]
Since we now have Cyclones that can deal with air units, we don't need to prepare as much against them. It hurts badly our economy to build an engineering bay, a turret and reasearch the hi-sec auto-tracker that early. We should think about logical conditions to decide when to build them.

I'd suggest to wait until our first expand is started.

**Comment by Unusual229** [comment]
Hi-sec auto-tracker might not be useful at all. How often do enemies get in range of our turrets, but wouldn't be without the upgrade? Guessing its close to never.

If we have a cyclone, we are not necessarily safe since its likely in the enemy base. The only real reason to build turrets is against Oracles, Banshee or Mutalisk. The issue is that, for both the Oracle and Banshee, if we don't have turrets when they arrive, we are in trouble. We could lose half or an entire mineral line before a cyclone comes back home.

**Comment by RaphaelRoyerRivard** [comment]
We could probably build the turrets and upgrade only against these units. We rarely get attacked because we fight in their bases and when we get counter attack, it's almost always only by ground units.

**Comment by Unusual229** [comment]
Normally Oracles and Banshees hit you by surprise, there would be no time for turrets. Mutalisk there is alsmost always time to build them.
Since no one is making Oracles or Banshees currently, we could change the logic, but as soon as someone does, we will be hit hard.

**Comment by RaphaelRoyerRivard** [comment]
Since our workers will try to avoid the enemy influence that comes from the
air, we probably wouldn't suffer a big loss of workers, but it would
temporarily prevent us from mining in that base. With Cyclones and Vikings,
we would probably be able to defend well enough to not lose the game right
away, but we'll still need to see.
