### ISSUE TITLE
Parse opponent id and choose strategy accordingly

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#531]

**Comment by Unusual229** [comment]
Could we not do this? I'd rather figure out how to randomize our id so we can't be voluntarily countered.

**Comment by RaphaelRoyerRivard** [comment]
We can't, it's generated from the ladder manager and we have no power over it. So we might as well use it for the tournament so we don't lose all our games the same way and when we find a build that works against the current bot we are facing, we do it again next match.

**Comment by Unusual229** [comment]
Should be in Tournement mode only (#define whatever), otherwise it might be annoying when testing/developing.
Create a file somewhere to keep track of the Opponent ID, our used strategy and the result of our last fight as a JSON. We already have code to read and parse JSON so it should be rather easy to get the data back (for the BotConfigs). Might want to consider random race in the future. Could keep track of our win rate per strategy, though it isn't entirely trustable for a tournament since the bots will change anyway.
Will need to modify the StrategyManager so it reads the JSON and chooses the strategy.
Even if we currently only have two strategies, we will need to keep track of which strategy we used when we lost a game, we will default to (A) and if (A) fails, we use (B). But if we lose with (B), we should go back to (A) (maybe?).
We should display an error message if we are unable to create or write into the file, this way whoever handles the tournament should be aware there is an issue before the tournament starts (when we tests the bot is working).

**Comment by RaphaelRoyerRivard** [comment]
OpponentId is now parsed and available via `CCBot::GetOpponentId()`. The available strategies are listed by the `StartingStrategy` enum (note that `PROXY_REAPERS` is not yet coded).
