### ISSUE TITLE
Detect ties

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#726]
They could either be considered as a new result type or as a lose.

**Comment by Unusual229** [comment]
If it is simple, tie should be a third type.
If we give ties a positive value (less than wins though), it will have the bot focus on not losing.
If we give ties a negative value (less than loses), it will have the bot focus on winning.

"Not losing" might be best for the ladder?
"Winning" is of course best for the tournaments, since ties will not be shown anyway.

**Comment by RaphaelRoyerRivard** [comment]
Managing ties shouldn't be hard, what is hard is detecting them.
