### ISSUE TITLE
Our bases should be lifted when they are attacked by ground units

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#760]

**Comment by Unusual229** [comment]
Careful not to lift for just a few ground unit. Might only want to lift when at 50-75% health so we don't lift for a handful of zerglings.
Lifting a CC might have unexpected impacts on :
- Unit production, not sure we do validate the building isn't lifted, might not matter.
- We might try to call down mules, not sure it matters.
- Would still be considered valid to scan, could cause issues since the scan wouldn't happen. Even if we don't use scans right now, we probably want to handle this now, since its easy and we will likely forget when we start using scans.
- Should check for other unexpected impacts that could be related to our occupied bases.

We might want to have code that escapes all the workers to the closest safe base.
